---
- name: Forwarding IPv4 and letting iptables see bridged traffic
  ansible.builtin.copy:
    src: modules-load.conf
    dest: /etc/modules-load.d/k8s.conf
    owner: root
    group: root
    mode: '0644'

- name: Load module overlay
  community.general.modprobe:
    name: overlay
    state: present

- name: Load module br_netfilter
  community.general.modprobe:
    name: br_netfilter
    state: present

- name: Sysctl params required by setup
  ansible.builtin.copy:
    src: sysctl.conf
    dest: /etc/sysctl.d/k8s.conf
    owner: root
    group: root
    mode: '0644'
  notify: Reload sysctl

- name: Kube images
  ansible.builtin.command: kubeadm config images pull
