---
all:
  vars:
    ansible_user: agat
  children:
    etcd:
      hosts:
        192.168.10.[113:115]:
    master:
      hosts:
        192.168.10.[113:115]:
    node:
      hosts:
        192.168.10.[116:118]:
    # yandex:
    #   vars:
    #     ansible_user: ansible
    #     ansible_port: 22
    #     ansible_ssh_private_key_file: '{{ inventory_dir }}/group_vars/id_ed25519'
    #   hosts: 158.160.11.115
