---
all:
  vars:
    ansible_port: 22
  children:
    etcd:
      hosts:
        192.168.10.[113:115]:
    master:
      hosts:
        192.168.10.[113:115]:
    node:
      hosts:
        192.168.10.[116:118]:
